// Generated wrapper config for Prisma CLI (JS version of prisma.config.ts)
require("dotenv").config();

module.exports = {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL env var if set, otherwise default to a local SQLite file
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
};
("use strict");
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
const config_1 = require("prisma/config");
exports.default = (0, config_1.defineConfig)({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (0, config_1.env)("DATABASE_URL"),
  },
});
